---
title: "Sensitivity Analysis Results"
author: "Alex Ehrens"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# attach packages
library(raster) 
library(tidyverse)
library(here)
library(sf)
library(fasterize)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
```

```{r}
# there are many rasters to read in, so want to stack them into one raster
sa_files <- list.files(path = here("sensitivity_iterations", "sensitivity_iterations"), pattern = "*tif", full.names = TRUE)

sa_stack <- raster::stack(sa_files)

# write raster stack
writeRaster(sa_stack, filename = "sensitivity_analysis_stack.tif", options = "INTERLEAVE=BAND", overwrite = TRUE)
```

```{r}
 # create a function to determine whether a species is present (value >0.6) or not in a given location
is_present <- function(x, thresh = 4){
  y <- ifelse(x >= thresh, 1, 0)
  return(y)
}

# run the function using the stack of rasters
sa_good <- calc(sa_stack, fun = is_present)

earth <- ne_countries(scale = "medium", returnclass = "sf") %>% 
  st_as_sf()

# sum to find the total richness of species in each raster cell
sa_total <- calc(sa_good, fun = sum, na.rm = TRUE) %>% 
  projectRaster(crs = crs(earth))

writeRaster(sa_total, filename = "sensitivity_analysis_results.tif", options = "INTERLEAVE=BAND", overwrite = TRUE)
# exploratory plot of the cetacean species richness raster
plot(sa_total)
```

```{r}
# turn raster stack into data frame for plotting and mutate a column with the sum of present species
sa_df <- rasterToPoints(sa_total) %>% 
  as.data.frame()

# set 0 values for sum to NA and then remove those cells so they don't show up on top of coastline map
sa_df$layer[sa_df$layer <= 0] <- NA

sa_df <- sa_df %>% 
  na.omit(layer)

# read in subbasin boundary shapefiles
chowchilla <-
    st_read(here("chowchilla_project", "chowchilla_project.shp")) %>% 
    st_transform(crs = crs(earth))

madera <-
    st_read(here("madera_project", "madera_project.shp")) %>% 
    st_transform(crs = crs(earth))

subbasins <- rbind(chowchilla, madera) %>%
    rename("name" = "Basin_Su_1")

ggplot() +
  geom_sf(data = subbasins, fill = "white") +
  coord_sf(xlim = c(-120.56,-119.7), ylim = c(36.79,37.2),
           expand = 0) +
  geom_tile(data = sa_df, aes(x = x, y = y, fill = layer)) +
  scale_fill_gradientn(colors = c("firebrick", "orange", "gold", "lightgreen", "darkgreen")) +
  theme_void()+
  labs(fill = "Number of \niterations \nresulting in \n'high priority' \nscore",
       title = "Sensitivity Analysis Results")+
  theme(plot.title = element_text(hjust = 0.7,
                                  size = 20),
        legend.title = element_text(size = 14))

ggsave("sa_results_full_white.png", height = 6, width = 9)

```

```{r}
### make version with only top 20% of sites pulled out
sa_top20 <- sa_df %>% 
  filter(layer > 0) %>% 
  slice_max(order_by = layer, prop = 0.2)

ggplot() +
  geom_sf(data = subbasins, fill = "white") +
  coord_sf(xlim = c(-120.56,-119.7), ylim = c(36.79,37.2),
           expand = 0) +
  geom_tile(data = sa_top20, aes(x = x, y = y, fill = layer)) +
  scale_fill_gradientn(colors = c("lightgreen", "darkgreen")) +
  theme_void()+
  labs(fill = "Number of \niterations \nresulting in \n'high priority' \nscore",
       title = "Sensitivity Analysis Results - Top 20%")+
  theme(plot.title = element_text(hjust = 0.7,
                                  size = 20),
        legend.title = element_text(size = 14))

ggsave("sa_results_20_white.png", height = 6, width = 9)
```

